package utils;

import org.apache.commons.lang3.StringUtils;
import models.testcases.TestCase;

import io.swagger.v3.oas.models.PathItem.HttpMethod;

import org.testng.log4testng.Logger;

import java.io.FileWriter;
import java.util.HashMap;
import java.util.Map.Entry;
import java.io.File;

import static utils.FileManager.checkIfExists;

import static org.apache.commons.lang3.StringEscapeUtils.escapeJava;

/**
 * This class defines a test writer for the REST Assured framework. It creates a Java class with TestNG test cases
 * ready to be executed.
 *
 * @author sherry li
 */
public class RESTAssuredWriter {

    private boolean OAIValidation = true;
    private boolean logging = false;                // Log everything (ONLY IF THE TEST FAILS)

    private String specPath;                        // Path to OAS specification file
    private String targetDirJava;                    // Path to target Java dir (where tests are generated)
    private String className;                        // Test class name
    private String testId;                            // Test suite ID
    private String packageName;                        // Package name
    private String baseURI;                            // API base URI
    private boolean logToFile;                        // If 'true', REST-Assured requests and responses will be logged into external files
    private String proxy;                            // Proxy to use for all requests in format host:port
    private String APIName;                            // API name (necessary for folder name of exported data)

    private boolean isInternalDLB = true;              //API connected to external DLB or internal DLBs
    private static final Logger logger = Logger.getLogger(RESTAssuredWriter.class);

    private boolean jwtRequired = false;

    private HashMap mapping = ReplaceVariables.fillReplaceMap();

    public RESTAssuredWriter(String strAPIName, String generateClassName, boolean isInternallDLB, boolean jwt, String targetDirJava, boolean logToFile) {
        //this.spec = new OpenAPISpecification(specPath);
        this.targetDirJava = targetDirJava;
        this.logToFile = logToFile;
        this.isInternalDLB = isInternallDLB;
        this.APIName = strAPIName;
        this.jwtRequired = jwt;
        //this.baseURI =
        this.packageName = strAPIName.replace("-", ".");
        this.className = generateClassName;//"AutoGeneratedCaseTest";
    }

    public void write(TestCase[] testCases) {

        // Initializing content
        String contentFile = "";
        // Generating imports
        contentFile += generateImports(this.packageName);
        // Generate className
        contentFile += generateClassName(className);

        // Generate attributes
        contentFile += generateAttributes(specPath);

        // Generate variables to be used.
        contentFile += generateSetUp(baseURI);

        // Generate tests
        int ntest = 1;
        for (TestCase t : testCases)
            contentFile += generateTest(t, ntest++);

        // Close class
        contentFile += "}\n";
        //Save to file
        saveToFile(targetDirJava, className, contentFile);
    }

    private String generateImports(String packageName) {
        String content = "";

        if (packageName != null)
            content += "package " + packageName + ";\n\n";

        content += "import io.restassured.RestAssured;\n"
                + "import io.restassured.builder.ResponseSpecBuilder;\n"
                + "import io.restassured.specification.ResponseSpecification;\n"
                + "import org.hamcrest.Matchers;\n"
                + "import org.json.JSONObject;\n"
                + "import org.testng.annotations.BeforeClass;\n"
                + "import org.testng.annotations.Test;\n"
                + "import org.testng.Assert;\n"
                + "import utils.*;\n"
                + "import base.BaseTest;\n"
                + "import org.testng.log4testng.Logger;\n"
                + "import static org.hamcrest.Matchers.equalTo;\n"
                + "import static io.restassured.path.json.JsonPath.with;\n";

        content += "\n";

        return content;
    }

    private String generateClassName(String className) {
        return "\n"
                + "public class " + className + " extends BaseTest  {\n\n";
    }

    private String generateAttributes(String specPath) {
        String content = "";
        content += "\tprivate static final Logger logger= Logger.getLogger(" + className + ".class);\n";
        content += "\n";
        return content;
    }

    private String generateSetUp(String baseURI) {
        String content = "";
        content += "\t@BeforeClass\n"
                + "\tpublic  void setUp() {\n";
        content += "\t\tsuper.setUp();\n";
        content += "\t}\n\n";
        return content;
    }

    private String generateTest(TestCase t, int instance) {
        String content = "";
        if (t.getResponseCheck() != null && !t.getResponseCheck().isEmpty()) {
            content += generateResponseSpec(t, instance);
        }
        // Generate test method header
        content += generateMethodHeader(t, instance);

        // Generate test case ID (only if stats enabled)
        content += generateTestCaseId(t, instance);
        content += generateMethodAttributes(t);
        // Generate the start of the try block
        content += generateTryBlockStart();

        // Generate RESTAssured object pointing to the right path
        content += generateRESTAssuredObject(t);

        //Generate shared parameters --client_id, client_secret,authorization
        content += generateAuthParameters(t);
        // Generate header parameters
        content += generateHeaderParameters(t);

        // Generate query parameters
        content += generateQueryParameters(t);

        // Generate path parameters
        content += generatePathParameters(t);

        //Generate form-data parameters
        content += generateFormParameters(t);

        content += generateBodyParameters(t);
        //generate body arrays if body is array
        if(t.getBodyJSONArray()!=null && !t.getBodyJSONArray().isEmpty()) {
            content += generateBodyJSONArrayParameters(t);

        }

        // Generate HTTP request
        content += generateHTTPRequest(t);

        content += generatePostResponseValidation(t);

        if(t.getResponseToGlobalVariables()!=null){
            content +=generateResponseToGlobalVariables(t);
        }

         if (t.getSchemaCheckEnabled()) {
            content += generatePostResponseSchemaValidation(t);

        }

        // Generate the end of the try block, including its corresponding catch
        content += generateTryBlockEnd();
        // Close test method
        content += "\t}\n\n";
        return content;
    }

    //create response spec for test validation
    private String generateResponseSpec(TestCase t, int instance) {

        String content = "\tpublic static ResponseSpecification " + t.getTestName() + "_spec() {\n";

        content += "\treturn new ResponseSpecBuilder()\n";
        for (Entry<String, Object> param : t.getResponseCheck().entrySet()) {

            if (param.getKey().toLowerCase().indexOf("body.") == 0) { //body string
                String key = param.getKey().replace("body.", "");
                if (StringUtils.isNumeric(param.getValue().toString())) {
                    content += "\t\t\t\t.expectBody(\"" + key + "\", equalTo(" + param.getValue() + "))\n";

                } else {
                    content += "\t\t\t\t.expectBody(\"" + key + "\", equalTo(\"" + param.getValue() + "\"))\n";
                }

            } else if (param.getKey().equalsIgnoreCase("responseTime")) {
                content += "\t\t\t\t.expectResponseTime(Matchers.lessThan(" + param.getValue() + "L))\n";

            } else if (param.getKey().equalsIgnoreCase("statusCode")) {
                content += "\t\t\t\t.expectStatusCode(" + param.getValue() + ")\n";
            } else {

            }
        }
        content += "\t\t\t\t.build();\n";
        content += "\t }\n";
        return content;
    }

    private String generateMethodHeader(TestCase t, int instance) {
        return "\t@Test(priority="+instance+", enabled=" + t.getTestStatus() + ")\n" +
                "\tpublic void " + t.getTestName() + "() {\n";
    }

    private String generateMethodAttributes(TestCase t) {
        String content = "";
        //GET THE FULL path of the request endpoint
        if (isInternalDLB) { //external DLB
            content += "\t\tString endPoint=PropertiesReader.getBaseURL(testEnv,true," +jwtRequired +")+\""+ t.getbaseUri() + t.getPath() + "\";\n";

        } else { //internal DLB
            content += "\t\tString endPoint=PropertiesReader.getBaseURL(testEnv,false," +jwtRequired +")+\""+ t.getbaseUri() + t.getPath() + "\";\n";

           // content += "\t\tString endPoint=PropertiesReader.getBaseURL(testEnv,false,jwtRequired)+\"" + t.getbaseUri() + t.getPath() + "\";\n";
        }

        if (t.getSchemaCheckEnabled()) {
            content += "\t\tString SWAGGER_JSON_URL =\"" + t.getAPISchemaPath() + "\";\n";
        }
        return content;
    }

    private String generateTestCaseId(TestCase t, int instance) {
        String content = "";
        String testResultId = "";
        testResultId = (t.getId() == null || t.getId().isEmpty()) ? String.valueOf(instance) : t.getId();

        content += "\t\tString testResultId = \"" + testResultId + "\";\n\n";

        return content;
    }

    private String generateTryBlockStart() {
        return "\t\ttry {\n";
    }

    private String generateRESTAssuredObject(TestCase t) {
        String content = "";

        content += "\t\t\t String responseBody = RestAssured\n"
                + "\t\t\t.given().config(sslConfig)\n";

        if (logging && !logToFile)
            content += "\t\t\t\t.log().all()\n";

        return content;
    }

    private String generateAuthParameters(TestCase t) {
        String content = "";

        //for(Entry<String,String> param: t.getHeaderParameters().entrySet())
        if (t.getHeaderParameters() == null || t.getHeaderParameters().get("client_id") == null) { // if client_id was not set, use pre-defined client_id
            content += "\t\t\t\t.header(\"client_id\",getClientId())\n";

        }
        if (t.getHeaderParameters() == null || t.getHeaderParameters().get("client_id") == null) { // if client_secret was not set, use pre-defined client_id
            content += "\t\t\t\t.header(\"client_secret\",getClientSecret())\n";

        }
        if (t.getAuthParameters() != null && t.getAuthParameters().size() != 0) {
            if ((t.getParameterValue("auth", "type").trim().equalsIgnoreCase("staffToken")) && (t.getParameterValue("auth", "ocvId").trim() != "")) {
                content += "\t\t\t\t.header(\"Authorization\",\"Bearer \"+getFakeStaffToken(\"" + t.getParameterValue("auth", "ocvId") + "\"))\n";

            } else if ((t.getParameterValue("auth", "type").trim().equalsIgnoreCase("userJWT")) && (t.getParameterValue("auth", "ocvId").trim() != "")) {
                content += "\t\t\t\t.header(\"Authorization\",\"Bearer \"+getFakeUserJWT(\"" + t.getParameterValue("auth", "ocvId") + "\"))\n";

            } else if ((t.getParameterValue("auth", "type").trim().equalsIgnoreCase("systemToken")) && (t.getParameterValue("auth", "forgeClientId").trim() != "")) {
                content += "\t\t\t\t.header(\"Authorization\",\"Bearer \"+getFakeSystemToken(\"" + t.getParameterValue("auth", "forgeClientId") + "\"))\n";
            } else if ((t.getParameterValue("auth", "type").trim().equalsIgnoreCase("azureIDToken")) ) {
                content += "\t\t\t\t.header(\"Authorization\",\"Bearer \"+getAzureIDToken())\n";
            } else {
                System.out.println("Invalid authentication!");
            }
        }
        return ReplaceVariables.replaceTag(content,mapping);
    }

    private String generateHeaderParameters(TestCase t) {
        String content = "";
        if (t.getHeaderParameters() != null) {
            for (Entry<String, String> param : t.getHeaderParameters().entrySet())
                content += "\t\t\t\t.header(\"" + param.getKey() + "\", \"" + escapeJava(param.getValue()) + "\")\n";
        }
        return ReplaceVariables.replaceTag(content,mapping);
    }

    private String generateQueryParameters(TestCase t) {
        String content = "";
        if (t.getQueryParameters() != null) {
            for (Entry<String, String> param : t.getQueryParameters().entrySet())
                content += "\t\t\t\t.queryParam(\"" + param.getKey() + "\", \"" + escapeJava(param.getValue()) + "\")\n";
        }
        return ReplaceVariables.replaceTag(content,mapping);

    }

    private String generatePathParameters(TestCase t) {
        String content = "";
        if (t.getPathParameters() != null) {
            for (Entry<String, String> param : t.getPathParameters().entrySet())
               // content += "\t\t\t\t.pathParam(\"" + param.getKey() + "\", \"" + escapeJava(param.getValue().replace("{", "")) + "\")\n";
                content += "\t\t\t\t.pathParam(\"" + param.getKey() + "\", \"" + escapeJava(param.getValue()) + "\")\n";

        }

        return ReplaceVariables.replaceTag(content,mapping);
    }

    private String generateFormParameters(TestCase t) {

        if (t.getFormParameters() == null) {
            return "";
        }
        String content = "";
        if (t.getFormParameters().entrySet().stream().anyMatch(x -> checkIfExists(x.getValue())))
            content += "\t\t\t\t.contentType(\"multipart/form-data\")\n";
        else if (!t.getFormParameters().isEmpty())
            content += "\t\t\t\t.contentType(\"application/x-www-form-urlencoded\")\n";

        for (Entry<String, String> param : t.getFormParameters().entrySet()) {
            content += new File(param.getValue()).exists() ? "\t\t\t\t.multiPart(\"" + param.getKey() + "\", new File(\"" + escapeJava(param.getValue()) + "\"))\n"
                    : "\t\t\t\t.formParam(\"" + param.getKey() + "\", \"" + escapeJava(param.getValue()) + "\")\n";
        }

        return ReplaceVariables.replaceTag(content,mapping);
    }

    private String generateBodyParameters(TestCase t) {
        if (t.getBodyParameters() == null) {
            return "";
        }
        String content = "";

        if ((t.getFormParameters() == null || t.getFormParameters().size() == 0) &&
                t.getBodyParameters() != null &&
                (t.getMethod().equals(HttpMethod.POST) || t.getMethod().equals(HttpMethod.PUT)
                        || t.getMethod().equals(HttpMethod.PATCH) ||
                        (t.getBodyParameters() != null && t.getMethod().equals(HttpMethod.DELETE)))){
            if(t.getInputFormat()!=null && !t.getInputFormat().isEmpty()){
                content += "\t\t\t\t.contentType(\"" + t.getInputFormat() + "\")\n";
            }
        }
        if (t.getBodyParameters() != null && t.getBodyParameters().size()!=0) {
            String strBody = JSONManager.convertToStringJSON(t.getBodyParameters());
            String convertedBody = strBody.replace("\"", "\\\"");
            content += "\t\t\t\t.body(\"" + convertedBody + "\")\n";
        }
        return ReplaceVariables.replaceTag(content,mapping);
    }
    //when body is JSONArray,need do special process
    private String generateBodyJSONArrayParameters(TestCase t) {
        if (t.getBodyJSONArray() == null) {
            return "";
        } else {
            String content = "";
            content += "\t\t\t\t.body(\"" +  escapeJava( t.getBodyJSONArray().toString()) + "\")\n";
            return content;
            //return ProcessVariables.replaceTag(content,mapping);
        }
     }

    private String generateHTTPRequest(TestCase t) {
        String content = "\t\t\t.when()\n";
        content += "\t\t\t\t." + t.getMethod().name().toLowerCase() + "(endPoint)\n";
        content += "\t\t\t.then()";
        content += "\n";
        return content;
    }

    private String generatePostResponseValidation(TestCase t) {
        String content = "";
        if (t.getResponseCheck() != null && !t.getResponseCheck().isEmpty()) {
            content += "\t\t\t\t.spec(" + t.getTestName() + "_spec())\n";
        } else {
            content += "\t\t\t\t.statusCode(" + Integer.parseInt(t.getStatusCode()) + ")\n";
        }
        content += "\t\t\t\t.extract().response().asString();\n\n";
        return content;
    }

    //when response value need to write to global variables,so that if could be chained to next request.
    private String generateResponseToGlobalVariables(TestCase t) {
        String content = "";
        if (t.getResponseToGlobalVariables() != null) {
            System.out.println("create global variables");
            for (Entry<String, String> param : t.getResponseToGlobalVariables().entrySet()) {
                content += "\t\t\t\t GlobalVariables.addGlobalVariables(\"" + param.getValue() + "\", with(responseBody).get(\"" + param.getKey()+"\").toString());\n";
                content += "\t\t\t\t GlobalVariables.flush();\n";
            }
       }
        return content;
    }
    private String generatePostResponseSchemaValidation(TestCase t) {
        String content = "";
        content += "\t\t\t\tAssert.assertTrue(utils.JsonSchemaValidator.validateSchemaFromAPISpec(SWAGGER_JSON_URL,responseBody,\"" + t.getPath() + "\",\"" + t.getMethod() + "\",\"" + t.getStatusCode() + "\",\"" + t.getOutputFormat() + "\")) ;\n;\n";
        return content;
    }

    private String generateTryBlockEnd() {
        return "\t\t} catch (RuntimeException ex) {\n"
                + "\t\t\tSystem.err.println(ex.getMessage());\n"
                + "\t\t\tlogger.error(ex.getMessage());\n"
                + "\t\t}\n";
    }

    //write the generated test cases to files in corresponding packages
    private void saveToFile(String path, String className, String contentFile) {
        String finalPath = path + "/" + APIName.replace("-", "/");
        try (FileWriter testClass = new FileWriter(finalPath + "/" + className + ".java")) {
            testClass.write(contentFile);
            testClass.flush();
        } catch (Exception ex) {
            logger.error("Error writing test file");
            logger.error("Exception: ", ex);
        }
    }

    public boolean OAIValidation() {
        return OAIValidation;
    }

    public void setOAIValidation(boolean oAIValidation) {
        OAIValidation = oAIValidation;
    }

    public boolean isLogging() {
        return logging;
    }

    public void setLogging(boolean logging) {
        this.logging = logging;
    }

    public String getTargetDirJava() {
        return targetDirJava;
    }

    public void setTargetDirJava(String targetDirJava) {
        this.targetDirJava = targetDirJava;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getBaseURI() {
        return baseURI;
    }

    public void setBaseURI(String baseURI) {
        this.baseURI = baseURI;
    }

    public String getAPIName() {
        return APIName;
    }

    public void setAPIName(String APIName) {
        this.APIName = APIName;
    }

    public void setTestId(String testId) {
        this.testId = testId;
    }

    public String getProxy() {
        return proxy;
    }

    public void setProxy(String proxy) {
        this.proxy = proxy;
    }
}
